#+title: Exercises
#+PROPERTY: header-args :results raw verbatim output :post output_drawer(data=*this*) :noweb strip-export

#+NAME: output_drawer
#+BEGIN_SRC shell :var data="" :exports none :results silent :results output :post
echo ':results:'
echo '#+HTML: <details>'
echo '#+HTML: <summary>Output</summary>'
echo '#+BEGIN_SRC'
echo -n "$data"
echo '#+END_SRC'
echo '#+HTML: </details>'
echo ':end:'
#+END_SRC


#+NAME: session_output_drawer
#+BEGIN_SRC shell :var data="" :exports none :results silent :results output :post
echo ':results:'
echo '#+HTML: <details>'
echo '#+HTML: <summary>Output</summary>'
echo '#+BEGIN_SRC'
echo "$data"
echo '#+END_SRC'
echo '#+HTML: </details>'
echo ':end:'
#+END_SRC


* Number Guesser
** Spec
This program plays a game with the user. The user thinks of a number between one and a hundred. The program guesses that number, and asks whether the guess is correct. The player answers ~y~ or ~n~, for yes or no. If the guess is not correct, the program asks whether the player's number is higher or lower. The player answers ~h~ or ~l~, for higher or lower respectively. This continues until the program guesses the number successfully, or there is no possible number it could be. The program should never guess a number that is impossible if the player has answered honestly the entire time without changing the number.
** Example
The following is an example of what it might look like to run the program.

#+NAME: fake-inputs-number-guesser
#+BEGIN_SRC python :exports none :results silent
def input(prompt):
    inputs = [
        "n",
        "h",
        "n",
        "l",
        "n",
        "l",
        "n",
        "h",
        "y"
    ]
    result = inputs[input.counter]
    input.counter = (input.counter + 1) % len(inputs)
    print(prompt + result)
    return result
input.counter = 0
#+END_SRC

#+BEGIN_SRC python :exports output
<<fake-inputs-number-guesser>>
# TODO
#+END_SRC

#+RESULTS:
:results:
#+HTML: <details>
#+HTML: <summary>Output</summary>
#+BEGIN_SRC
#+END_SRC
#+HTML: </details>
:end:
